version: "{build}"
skip_branch_with_pr: true
skip_tags: true
build: off

environment:
  matrix:
    - nodejs_version: stable
    - nodejs_version: 4

platform:
  - x64
  - x86

# Install scripts. (runs after repo cloning)
install:
  # install Node.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git --version
  #- node -p process.env
  # install modules
  - npm install --ignore-scripts

# to run your custom scripts instead of automatic tests
test_script:
  - npm test

# to run your custom scripts instead of provider deployments
after_test:
  - npm run report-coverage
  - bin\bash.cmd -c "[ ! `git diff --name-only -- src/data-cache.json` ]" || appveyor PushArtifact src\data-cache.json
